### PR TITLE
Use window-start to begin rendering attributres

### PR DESCRIPTION
**Pull request by aikrahguzar**
This should fix the remaining problem with attribute rendering. This also makes attribute rendering do less work and only render attributes for the one file above and one below the region visible in the window. That doesn't result in any problems form what I can see.

### CODE REVIEW

**Comment by alexluigit** [comment]
Thanks for the PR, I've actually tried `window-start/end` several times in the past, unfortunately it was pretty unreliable in this use case, although it looked like a much saner tool for the job. It causes flicker after performing a long distance navigation command such as `beginning/end-of-buffer`, I guess the reason is the inconsistency between `redisplay` and `set-window-start`.  The flicker also happens for the `group-previous/next` command when there are many files in a group.  The other problem with using `window-start` is that it does not guaranteed a fully rendered "page", it might look differently for users have different window scroll settings.  For these reasons I'm afraid I have to reject this PR, but I'm still willing to improve the rendering function once we got better implementations.

Use `window-height` to replace `frame-height` is a good one though.

**Comment by aikrahguzar** [comment]
> Thanks for the PR, I've actually tried `window-start/end` several times in the past, unfortunately it was pretty unreliable in this use case, although it looked like a much saner tool for the job. It causes flicker after performing a long distance navigation command such as `beginning/end-of-buffer`, I guess the reason is the inconsistency between `redisplay` and `set-window-start`. The flicker also happens for the `group-previous/next` command when there are many files in a group. The other problem with using `window-start` is that it does not guaranteed a fully rendered "page", it might look differently for users have different window scroll settings. For these reasons I'm afraid I have to reject this PR, but I'm still willing to improve the rendering function once we got better implementations.
> 
> Use `window-height` to replace `frame-height` is a good one though.

I can reproduce the problem with long distance navigation. Indeed the manual has this under `window-start`

```
Nothing except redisplay automatically changes the window-start position; if you move point,
do not expect the window-start position to change in response until after the next redisplay.
```
which is what happens with long distance navigation. 

I think the solution to that problem is to have `(redisplay)` at the start of `dirvish-update-body-h`. The documentation of `post-command-hook` says
```
It is a bad idea to use this hook for expensive processing.  If unavoidable, wrap your code in 
(while-no-input (redisplay) CODE) to avoid making Emacs unresponsive while the user types.
``` 
so I think that call to `redisplay` is completely fine and it does solve the issue with navigation for me.

But I don't understand the issue with scrolling, so maybe I am missing something more.

**Comment by alexluigit** [comment]
> I think the solution to that problem is to have (redisplay) at the start of `dirvish-update-body-h`

I had tried this too before. The flicker persists when opening a directory (with # of files > window height). The other problem of doing so is the wobbling on window scrolling (like when you hold n/p, or j/k in evil). Even if it works, it still introduces complexities that can be avoided in the first place.

**Comment by aikrahguzar** [comment]
> I had tried this too before. The flicker persists when opening a directory (with # of files > window height). The other problem of doing so is the wobbling on window scrolling (like when you hold n/p, or j/k in evil). Even if it works, it still introduces complexities that can be avoided in the first place.

Makes sense and I think your new solution of removing the files in hidden groups works better in that now those hidden files can't be accidentally marked.

**Pull request closed without merging**
